FROM brumbrum/python3

# RUN apk update && apk addbash build-base python3-dev libffi-dev

# WORKDIR /app
RUN git clone 
COPY . ./

# RUN pip install -r requirements.txt
# RUN pip install .

# RUN chmod +x ./run.sh

CMD ["chatter.py"]