FROM brumbrum/python3

# WORKDIR /app
COPY . ./
# #Install git
# RUN apt-get update && apt-get install -y git && git clone https://github.com/mostafa-metwaly/Distributed_systems_2021
# #Set working directory
# WORKDIR /Distributed_systems_2021
ENTRYPOINT [ "python3"   ]

CMD ["server.py" ]

